loom_remote_user: loom
server_settings_home: "/home/{{loom_remote_user}}/.loom"
client_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_CLIENT_USES_SERVER_INTERNAL_IP')|default(false, true)|bool}}"
worker_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_USES_SERVER_INTERNAL_IP')|default(false, true)|bool}}"
worker_connection_settings_file: "{{lookup('env','LOOM_GCLOUD_WORKER_CONNECTION_SETTINGS_FILE')|default('worker-connection-settings.conf', true)}}"

# GCE settings
disk_type: "{{lookup('env','LOOM_GCLOUD_SERVER_DISK_TYPE')|default('pd-standard', true)}}"
disk_size_gb: "{{lookup('env','LOOM_GCLOUD_SERVER_DISK_SIZE_GB')|default('10', true)}}"
gce_credential: "{{settings_home}}/{{resource_dir}}/{{lookup('env','LOOM_GCE_PEM_FILE')}}"
gce_email: "{{lookup('env','LOOM_GCE_EMAIL')}}"
gce_project: "{{lookup('env','LOOM_GCE_PROJECT')}}"
server_name: "{{lookup('env','LOOM_SERVER_NAME')}}"
instance_image: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_IMAGE')|default('centos-7', true)}}"
instance_type: "{{lookup('env','LOOM_GCLOUD_SERVER_INSTANCE_TYPE')}}"
network: "{{lookup('env','LOOM_GCLOUD_SERVER_NETWORK')}}"
subnetwork: "{{lookup('env','LOOM_GCLOUD_SERVER_SUBNETWORK')}}"
loom_tags: "{{lookup('env','LOOM_GCLOUD_SERVER_TAGS')|default('http-server', true)}}"
external_ip: "{{lookup('env','LOOM_GCLOUD_SERVER_EXTERNAL_IP')}}"
zone: "{{lookup('env','LOOM_GCLOUD_SERVER_ZONE')|default('us-central1-c', true)}}"
instance_name_max_length: "{{lookup('env','LOOM_GCLOUD_INSTANCE_NAME_MAX_LENGTH')|default(63,true)}}"
