---
- name: Create a new instance for the Loom server
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - include: tasks/gcloud_get_server_instance_name.yml
  - include: tasks/gcloud_create_instance.yml use_internal_ip={{client_uses_internal_ip}}
  - include: tasks/gcloud_configure_instance_ssh.yml use_internal_ip={{client_uses_internal_ip}}
  - name: Save server IP for worker.
    set_fact:
      server_ip_for_client: "{{groups['new_instances'][0]}}"
      server_ip_for_worker: "{{ (worker_uses_internal_ip) | ternary(gce_result.instance_data[0].private_ip, gce_result.instance_data[0].public_ip) }}"

- name: Create client connection settings, worker connection settings, and settings bundle
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - include: tasks/create_connection_settings.yml server_url={{server_protocol}}://{{server_ip_for_client}}:{{server_port}}
  - include: tasks/create_connection_settings.yml server_url={{server_protocol}}://{{server_ip_for_worker}}:{{server_port}} connection_settings_file={{worker_connection_settings_file}}
  - include: tasks/create_settings_bundle.yml

- name: Install Docker on the Loom server and add remote user to docker group.
  hosts: new_instances
  remote_user: "{{loom_remote_user}}"
  become: yes
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  roles:
  - {role: docker, when: "not lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')|bool"}
  - {role: docker-py, when: "not lookup('env', 'LOOM_GCLOUD_SERVER_SKIP_INSTALLS')|bool"}
  tasks:
  - include: tasks/gcloud_create_docker_group.yml

- name: Log into Google Container Registry.
  hosts: new_instances
  remote_user: "{{loom_remote_user}}"
  become: yes
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - include: tasks/gcloud_docker_login.yml

- name: Pull Docker images on the new instance.
  hosts: new_instances
  remote_user: "{{loom_remote_user}}"
  become: yes
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - include: tasks/pull_docker_images.yml

- name: Create directories and copy files to Loom server.
  hosts: new_instances
  remote_user: "{{loom_remote_user}}"
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - name: Create a settings directory on the server
    file:
      path: "{{server_settings_home}}"
      state: directory
  - name: Copy worker connection settings file from client to server
    synchronize:
      src: "{{settings_home}}/{{worker_connection_settings_file}}"
      dest: "{{server_settings_home}}"
  - name: Copy admin files directory from client to server
    synchronize:
      src: "{{settings_home}}/{{resource_dir}}/"
      dest: "{{server_settings_home}}/{{resource_dir}}"
  - name: Copy playbooks directory from client to server
    synchronize:
      src: "{{settings_home}}/{{loom_playbook_dir}}/"
      dest: "{{server_settings_home}}/{{loom_playbook_dir}}"
  - name: Set inventory files to be executable.
    file:
      path: "{{server_settings_home}}/{{loom_playbook_dir}}/*.py"
      state: directory
      mode: "a+x"
      recurse: yes
  - name: Copy server settings file from client to server.
    synchronize:
      src: "{{settings_home}}/{{server_settings_file}}"
      dest: "{{server_settings_home}}/{{server_settings_file}}"
  - name: Copy settings bundle file from client to server.
    synchronize:
      src: "{{settings_home}}/{{settings_bundle_file}}"
      dest: "{{server_settings_home}}/{{settings_bundle_file}}"

- name: Start the Loom server.
  hosts: new_instances
  remote_user: "{{loom_remote_user}}"
  become: yes
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  vars:
  - server_url: "{{lookup('ini', 'LOOM_SERVER_URL type=properties file='+settings_home+'/'+connection_settings_file)}}"
  tasks:
  - include: tasks/start_server_containers.yml

- name: Wait for Loom server to be ready.
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  vars:
  - server_url: "{{lookup('ini', 'LOOM_SERVER_URL type=properties file='+settings_home+'/'+connection_settings_file)}}"
  - host: "{{server_ip_for_client}}"
  tasks:
  - include: tasks/wait_for_server_to_start.yml
