---
- name: Start the various components of a loom server
  hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml
    - vars/local.yml
  vars:
    - host: 127.0.0.1
  tasks:
    - include: tasks/create_connection_settings.yml
    - include: tasks/create_settings_bundle.yml
    - include: tasks/start_server_containers.yml
    - include: tasks/wait_for_server_to_start.yml
