from django.test import TestCase

from api.test import fixtures
from api.models import *
from api.serializers.task_runs import *

class TestWorkerProcessSerializer(TestCase):

    def testUpdate(self):
        step = Step.objects.create(command='blank')
        step_run = StepRun.objects.create(template=step)
        task_run = TaskRun.objects.create(step_run=step_run)
        task_run_attempt = TaskRunAttempt.objects.create(task_run=task_run)
        
        s = WorkerProcessSerializer(
            task_run_attempt.worker_process,
            data={'status': 'running'})
        s.is_valid()
        s.save()
        self.assertEqual(task_run_attempt.worker_process.status, 'running')

    def testCreate(self):
        step = Step.objects.create(command='blank')
        step_run = StepRun.objects.create(template=step)
        task_run = TaskRun.objects.create(step_run=step_run)
        task_run_attempt = TaskRunAttempt.objects.create(task_run=task_run)

        # WorkerProcess was autogenerated with task_run_attempt.
        # We delete it so we can add it back in this test.
        task_run_attempt.worker_process.delete()
        
        s = WorkerProcessSerializer(
            data={'status': 'running'},
            context={'parent_field': 'task_run_attempt',
                     'parent_instance': task_run_attempt})
        s.is_valid(raise_exception=True)
        m = s.save()
        self.assertEqual(m.status, 'running')
