---
- name: Stop and/or cleanup a TaskAttempt on localhost
  hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml
    - vars/local.yml
  vars:
    task_attempt_id: "{{lookup('env', 'LOOM_TASK_ATTEMPT_ID')}}"
  tasks:
    - include: tasks/delete_task_attempt_container.yml
