---
- name: Delete all the components of a loom server
  hosts: localhost
  connection: local
  vars_files:
    - vars/common.yml
    - vars/local.yml
  tasks:
    - include: tasks/delete_server_containers.yml
    - include: tasks/delete_static_volumes.yml
    - include: tasks/delete_data_volumes.yml
