---
- name: Delete the Loom server.
  hosts: localhost
  connection: local
  vars_files:
  - vars/common.yml
  - vars/gcloud_server.yml
  tasks:
  - include: tasks/gcloud_get_server_instance_name.yml
  - include: tasks/gcloud_delete_instance.yml
