# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datanode',
            name='tree_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='run',
            name='tree_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
