  - name: Boot up a new instance
    gce:
      name: "{{instance_name}}"
      # "state: started" was not working as of ansible 2.3.1.0
      state: present
      image: "{{instance_image}}"
      disk_size: "{{disk_size_gb}}"
      persistent_boot_disk: True
      zone: "{{zone}}"
      machine_type: "{{instance_type if instance_type|trim else omit}}"
      network: "{{network if network|trim else omit}}"
      subnetwork: "{{subnetwork if subnetwork|trim else omit}}"
      service_account_email: "{{gce_email}}"
      credentials_file: "{{gce_credential}}"
      project_id: "{{gce_project}}"
      service_account_permissions: cloud-platform
      tags: "{{loom_tags if loom_tags|trim else omit}}"
      external_ip: "{{external_ip if external_ip|trim else omit}}"
      # ip_forward is required for by docker containers to access the internet
      ip_forward: true
    register: gce_result
    until: gce_result['state'] is defined and gce_result['state'] == "present"
    retries: 5

  - name: Add host IP to new_instances for downstream plays. Use internal or external IP depending on setting.
    add_host: hostname={{ (use_internal_ip) | ternary(item.private_ip, item.public_ip) }} groupname=new_instances
    with_items: '{{ gce_result.instance_data }}'
