# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 00:07
from __future__ import unicode_literals

import api.models.validators
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171003_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='notification_context',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True, validators=[api.models.validators.validate_notification_context]),
        ),
        migrations.RunSQL("UPDATE api_run SET notification_context = NULL WHERE notification_context = ''"),
    ]
