# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 22:02
from __future__ import unicode_literals

import api.models
import api.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fix_notification_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datanode',
            name='level',
        ),
        migrations.RemoveField(
            model_name='datanode',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='datanode',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='run',
            name='level',
        ),
        migrations.RemoveField(
            model_name='run',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='run',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='run',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file_relative_path',
            field=models.TextField(blank=True, default=b'', validators=[api.models.validators.validate_relative_file_path]),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datanode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='datanode',
            name='tree_id',
            field=models.CharField(default=api.models.uuidstr, max_length=255),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='data_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_resource', to='api.DataObject'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='upload_status',
            field=models.CharField(choices=[(b'incomplete', b'Incomplete'), (b'complete', b'Complete'), (b'failed', b'Failed'), (b'deleting', b'Deleting')], default=b'incomplete', max_length=16),
        ),
        migrations.AlterField(
            model_name='run',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.Run'),
        ),
        migrations.AlterField(
            model_name='runconnectornode',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskattemptinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskattemptoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='template',
            name='steps',
            field=models.ManyToManyField(related_name='parents', through='api.TemplateMembership', to='api.Template'),
        ),
        migrations.AlterField(
            model_name='templateinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='templatemembership',
            name='child_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_templates', to='api.Template'),
        ),
        migrations.AlterField(
            model_name='templatemembership',
            name='parent_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_templates', to='api.Template'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
    ]
