# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 05:08
from __future__ import unicode_literals

import api.models.base
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    TaskAttempt = apps.get_model('api', 'TaskAttempt')
    for task_attempt in TaskAttempt.objects.all():
        if task_attempt.task is not None:
            task_attempt.tasks.add(task_attempt.task)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180220_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_change', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.base._FilterMixin),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='tasks',
            field=models.ManyToManyField(related_name='all_task_attempts', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_on_tasks', to='api.TaskAttempt'),
        ),
        migrations.RunPython(forward),
        migrations.RemoveField(
            model_name='taskattempt',
            name='task',
        ),
        migrations.AddField(
            model_name='run',
            name='force_rerun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskfingerprint',
            name='active_task_attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fingerprint', to='api.TaskAttempt'),
        ),
    ]
