# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171117_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.Run'),
        ),
        migrations.AlterField(
            model_name='runconnectornode',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskattemptinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskattemptoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='taskoutput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='templateinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='data_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.DataNode'),
        ),
    ]
