# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 22:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='timeout_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='timeout_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='timeout_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datalabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='datatag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='runlabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='runtag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='templatelabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='templatetag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
    ]
