# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_fingerprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskattempt',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
