# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 18:38
from __future__ import unicode_literals

import api.models.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171117_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='file_relative_path',
            field=models.TextField(blank=True, default=b'', validators=[api.models.validators.validate_relative_file_path]),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='data_object',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_resource', to='api.DataObject'),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='upload_status',
            field=models.CharField(choices=[(b'incomplete', b'Incomplete'), (b'complete', b'Complete'), (b'failed', b'Failed'), (b'deleting', b'Deleting')], default=b'incomplete', max_length=16),
        ),
    ]
