# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 19:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180510_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='runconnectornode',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='runconnectornode',
            name='data_node',
        ),
        migrations.RemoveField(
            model_name='runconnectornode',
            name='run',
        ),
        migrations.AlterField(
            model_name='datalabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='datatag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='runlabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='runtag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='templatelabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='templatetag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[0-9a-zA-Z_\\-]*$', message=b'Only alphanumeric characters are allowed.')]),
        ),
        migrations.DeleteModel(
            name='RunConnectorNode',
        ),
    ]
