# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171129_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='in_external_storage',
            field=models.BooleanField(default=False),
        ),
    ]
