# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180711_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='imported',
        ),
        migrations.AlterField(
            model_name='run',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.Run'),
        ),
    ]
