# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_fileresource_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='level',
        ),
        migrations.RemoveField(
            model_name='run',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='run',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='run',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='run',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='api.Run'),
        ),
    ]
