# Generated by Django 2.1.7 on 2019-02-19 18:20

import api.models.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180711_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='datanode',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=16),
        ),
        migrations.AlterField(
            model_name='datatag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', message='Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='file_relative_path',
            field=models.TextField(blank=True, default='', validators=[api.models.validators.validate_relative_file_path]),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='source_type',
            field=models.CharField(choices=[('imported', 'Imported'), ('result', 'Result'), ('log', 'Log')], max_length=16),
        ),
        migrations.AlterField(
            model_name='fileresource',
            name='upload_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete'), ('failed', 'Failed'), ('deleting', 'Deleting')], default='incomplete', max_length=16),
        ),
        migrations.AlterField(
            model_name='run',
            name='postprocessing_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', max_length=255),
        ),
        migrations.AlterField(
            model_name='runinput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='runlabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='runoutput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='runtag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', message='Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='taskattemptinput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taskattemptoutput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taskinput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='taskoutput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='templateinput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
        migrations.AlterField(
            model_name='templatelabel',
            name='label',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='templatetag',
            name='tag',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z_\\-]*$', message='Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='type',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('string', 'String')], max_length=255),
        ),
    ]
