- name: Get password for GCR login.
  command: gcloud auth print-access-token
  register: gcrpassword
  register: result
  retries: 30
  until: result | succeeded
- name: Authenticate with GCR.
  docker_login:
    registry_url: https://gcr.io
    username: oauth2accesstoken
    password: "{{gcrpassword.stdout}}"
  register: result
  retries: 30
  until: result | succeeded
