# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170921_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datalabel',
            unique_together=set([('label', 'data_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='runlabel',
            unique_together=set([('label', 'run')]),
        ),
        migrations.AlterUniqueTogether(
            name='templatelabel',
            unique_together=set([('label', 'template')]),
        ),
    ]
