# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 23:22
from __future__ import unicode_literals

import api.models.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170927_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='notification_context',
            field=jsonfield.fields.JSONField(blank=True, validators=[api.models.validators.validate_notification_context]),
        ),
        migrations.AddField(
            model_name='task',
            name='analysis_failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='system_failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
