# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-02 23:19
from __future__ import unicode_literals

import api.models.validators
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170927_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='notification_context',
            field=jsonfield.fields.JSONField(blank=True, validators=[api.models.validators.validate_notification_context]),
        ),
    ]
