loom_remote_user: loom
worker_ssh_private_key_path_in_container: "/root/.ssh/{{lookup('env', 'LOOM_SSH_PRIVATE_KEY_NAME')}}"
ansible_ssh_private_key_file: "{{worker_ssh_private_key_path_in_container}}"
worker_uses_internal_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_USES_SERVER_INTERNAL_IP')}}"
worker_connection_settings_file: "{{lookup('env','LOOM_GCLOUD_WORKER_CONNECTION_SETTINGS_FILE')}}"

boot_disk_size_gb: "{{lookup('env','LOOM_GCLOUD_WORKER_BOOT_DISK_SIZE_GB')|default('10',true)}}"
boot_disk_type: "{{lookup('env','LOOM_GCLOUD_WORKER_BOOT_DISK_TYPE')}}"
cores: "{{lookup('env','LOOM_TASK_ATTEMPT_CORES')|default('1',true)}}"
external_ip: "{{lookup('env','LOOM_GCLOUD_WORKER_EXTERNAL_IP')}}"
gce_credential: "{{container_settings_home}}/{{admin_files_dir}}/{{lookup('env','LOOM_GCE_PEM_FILE')}}"
gce_email: "{{lookup('env','LOOM_GCE_EMAIL')}}"
gce_project: "{{lookup('env','LOOM_GCE_PROJECT')}}"
instance_image: "{{lookup('env','LOOM_GCLOUD_WORKER_INSTANCE_IMAGE')}}"
log_level: "{{lookup('env','LOOM_LOG_LEVEL')}}"
loom_docker_image: "{{lookup('env','LOOM_DOCKER_IMAGE')}}"
memory: "{{lookup('env','LOOM_TASK_ATTEMPT_MEMORY')|default('3.75',true)}}"
network: "{{lookup('env','LOOM_GCLOUD_WORKER_NETWORK')}}"
scratch_disk_mount_point: "{{lookup('env','LOOM_STORAGE_ROOT')}}"
scratch_disk_size_gb: "{{[lookup('env','LOOM_GCLOUD_WORKER_SCRATCH_DISK_MIN_SIZE_GB'), lookup('env','LOOM_TASK_ATTEMPT_DISK_SIZE_GB')] | max}}"
scratch_disk_type: "{{lookup('env','LOOM_GCLOUD_WORKER_SCRATCH_DISK_TYPE')}}"
step_name: "{{lookup('env','LOOM_TASK_ATTEMPT_STEP_NAME')}}"
subnetwork: "{{lookup('env','LOOM_GCLOUD_WORKER_SUBNETWORK')}}"
loom_tags: "{{lookup('env','LOOM_GCLOUD_WORKER_TAGS')}}"
task_attempt_id: "{{lookup('env', 'LOOM_TASK_ATTEMPT_ID')}}"
task_attempt_docker_image: "{{lookup('env','LOOM_TASK_ATTEMPT_DOCKER_IMAGE')}}"
worker_log_file: "{{lookup('env','WORKER_LOG_FILE')}}"
zone: "{{lookup('env','LOOM_GCLOUD_WORKER_ZONE')}}"
